- name: Test ssh connection to the server
  ping:

- name: Update & upgrade repository
  apt:
    update_cache: yes
    upgrade: yes
    autoremove: yes

- name: Add Docker GPG apt Key manually
  ansible.builtin.shell: |
    curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
  args:
    creates: /usr/share/keyrings/docker-archive-keyring.gpg
  become: true

- name: Add Docker Repository with signed-by option
  apt_repository:
    repo: "deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu focal stable"
    state: present

- name: Update apt and install docker-ce
  apt:
    name: docker-ce
    state: latest
    update_cache: true

- name: Install docker-compose
  apt:
    name: docker-compose
    state: latest
    update_cache: true

- name: Create "docker" group
  group:
    name: docker
    state: present

- name: Add remote "chirpstack" user to "docker" group
  user:
    name: "{{ansible_user}}"
    groups: docker
    append: yes
