- name: Single server chirpstack deployment
  hosts:
    - chirpstack
  become: "{{ become | default('yes') }}"
  vars_files:
    - vars/secrets.yml

  tasks:
    - name: Adiciona chave GPG do Docker manualmente
      ansible.builtin.shell: |
        curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
      args:
        creates: /usr/share/keyrings/docker-archive-keyring.gpg
      become: true

  roles:
    - base
    - chirpstack
    - nodered
    - monitoring
